### ISSUE TITLE
Does it work with a single line? Like LongfilenameABC...pdf

### ISSUE THREAD

**Issue by piggyslasher** [dibari/angular-ellipsis#18]
If I have the file extension (.pdf in this case) as a scope variable and want the file name to shrink and have ellipsis - is this possible?

On your live example I tried setting your max-height to 25 instead of 75 (using chrome dev tools) and it did not work. would it work on single line text if I tried?

**Comment by dibari** [comment]
If you're doing a single string of text with no spaces, the ellipsis won't wrap.  It uses spaces in the text block to find where to put the break.
