### ISSUE TITLE
jasmine should be in devDependencies 

### ISSUE THREAD

**Issue by mkoryak** [dibari/angular-ellipsis#21]
otherwise build tools pull it into the build, and it breaks stuff.

since this hasnt been updated in 2 years, I am forking it here:

https://github.com/HourlyNerd/angular-ellipsis
and registering it on bower as `hn-angular-ellipsis`

**Comment by MauMaGau** [comment]
Fixed in https://github.com/dibari/angular-ellipsis/pull/26

**Comment by mkoryak** [comment]
thanks

**Comment by mkoryak** [comment]
can you also make a new version on bower at some point, so i can stop using my fork

**Comment by MauMaGau** [comment]
Current version is `0.1.3` as of today.
