### ISSUE TITLE
XSS vulnerability

### ISSUE THREAD

**Issue by borislit** [dibari/angular-ellipsis#22]
Since Angular Ellipsis uses the actual value of ngBind attribute and then simply adds it to DOM using element.html(), this creates an XSS vulnerability as string can contain can script tags and is inserted as is into DOM. This can be confusing, as developers count on ngBind being sanitized  using SCE service by default.

IMO, since ngBind is utilized the way it is, there needs to be a check in code to see if ngSanitized is present and if it is - utilize it.

**Comment by MauMaGau** [comment]
Fixed by https://github.com/dibari/angular-ellipsis/pull/27
