### ISSUE TITLE
tag stable version

### ISSUE THREAD

**Issue by AprilArcus** [dibari/angular-ellipsis#23]
Could you please tag a stable version so that we can use npm to manage our dependency on this module? c.f.

http://stackoverflow.com/questions/14187956/npm-install-from-git-in-a-specific-version
https://github.com/2fdevs/bower-videogular/issues/7#issuecomment-104001052

**Comment by eranimo** [comment]
Also adding the distribution file to a package.json's main attribute would allow browserify support

**Comment by aseckel** [comment]
:+1:  please!

**Comment by sophlee** [comment]
:+1:

**Comment by AprilArcus** [comment]
Even without a `main:` attribute, you can always `require('angular-ellipsis/src/angular-ellipsis.js');`, but pinning our project's `package.json` manifest to a version number instead of a commit hash would be really helpful.

**Comment by MauMaGau** [comment]
Stable version is now tagged as 0.1.0
@eranimo I'm not overly familiar with package.json. I take it `main` points to the entry script? Would it look like:
```
"main": "src/angular-ellipsis.js"
```
