### ISSUE TITLE
Is this repo still maintained

### ISSUE THREAD

**Issue by MauMaGau** [dibari/angular-ellipsis#25]
Is this repo actively maintained? If not I'll happily fork and maintain a new version. Noticed there are some impressive performance improvements pull requests that ought to get merged. Would you mind me forking and creating a new bower package based on your work? Or even better to add me as an admin of this repo.

**Comment by dibari** [comment]
I haven't had any time lately, but I'd like to continue work on it as I have time.  Would it work to add you as a collaborator, or are you interested in forking it?

**Comment by MauMaGau** [comment]
Hey dibari, Collaborator would be great - mostly so I can test and merge the pending pull requests.

**Comment by dibari** [comment]
I added you as a collaborator - thanks for any work you can do.

**Comment by MauMaGau** [comment]
Thanks dibari. Just tagged the current version as 0.1.0.
