### ISSUE TITLE
Which is better? angular-ellipsis or ng-text-truncate?

### ISSUE THREAD

**Issue by stephen-cernota** [dibari/angular-ellipsis#41]
ng-text-truncate
https://github.com/lorenooliveira/ng-text-truncate

Demo
https://rawgit.com/lorenooliveira/ng-text-truncate/master/demo1.html

Why is angular-ellipsis more active and more popular?

**Comment by dibari** [comment]
From the looks of it, ng-text-truncate requires you to specify the maximum number of letters or words to display.  On the other hand, angular-ellipsis automatically truncates the visible text to the size of the containing element.  If you're dealing with dynamic text or multiple devices screen sizes, angular-ellipsis will be more flexible.
