### ISSUE TITLE
bower version is not the latest, doesn't include dibari:refresh-ellipsis

### ISSUE THREAD

**Issue by itay-sho** [dibari/angular-ellipsis#66]
I tried using this functionality from the bower version and it seems like it's not there yet, when I clone the repository from here it works, but only in the not-minified version

**Comment by jwhitmarsh** [comment]
👍  Can someone tag and publish the latest please? @dibari or @MauMaGau?

**Comment by ventralnet** [comment]
+1

**Comment by MauMaGau** [comment]
Updated to 0.1.7.

**Comment by MauMaGau** [comment]
It's up to @dibari to publish to npm.

**Comment by gurumvg** [comment]
@dibari @MauMaGau 
The latest angular-ellipsis@1.0.1 version too doesn't have `dibari:refresh-ellipsis` change.

In the source code downloaded from [tag/0.1.7 ](https://github.com/dibari/angular-ellipsis/releases/tag/0.1.7) the raw version has the `dibari:refresh-ellipsis` change but not the min version.

Any plans to push the latest changes to npm ?

**Comment by MauMaGau** [comment]
I'm afraid I no longer maintain this package. Unless @dibari says otherwise I would consider this package stale.

If there is an actively maintained fork then I'd be happy to link to that in the readme

**Comment by dibari** [comment]
Hi all, unfortunately I no longer maintain this package and I would consider it stale.  I'm happy to transfer it another maintainer if anyone is interested?
